services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dette
      POSTGRES_PASSWORD: dette
      POSTGRES_DB: dette
    ports:
      - '5432:5432'
    volumes:
      - dette_pg:/var/lib/postgresql/data
      - ./drizzle/0000_init.sql:/docker-entrypoint-initdb.d/0000_init.sql

volumes:
  dette_pg:
